kit/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :bags

  get 'welcome/index'

  root 'welcome#index'

end

kit/app/models/bag.rb
class Bag < ActiveRecord::Base
end

kit/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

kit/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

kit/app/controllers/bags_controller.rb
class BagsController < ApplicationController
  def new
    @bag = Bag.new
  end

  def edit
    @bag = Bag.find(params[:id])
  end

  def create
    @bag = Bag.new(bag_params)
    
    @bag.save
    redirect_to @bag
  end

  def update
    @bag = Bag.find(params[:id])

    if @bag.update(bag_params)
      redirect_to @bag
    else
      render 'edit'
    end
  end

  def show
    @bag = Bag.find(params[:id])
  end

  def index
    @bags = Bag.all
  end
 
  private
    def bag_params
      params.require(:bag).permit(:adv, :description, :link)
    end

end

kit/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

kit/app/helpers/application_helper.rb
module ApplicationHelper
end

kit/app/helpers/bags_helper.rb
module BagsHelper
end

kit/app/helpers/welcome_helper.rb
module WelcomeHelper
end

kit/app/views/bags/edit.html.erb
<table>
  <tr>
    <td>
      <h2>edit <strong><i>kit</i></strong></h2>  
    </td> 
  </tr>
  <tr>
    <td>
      <h6>last repacked <%= @bag.updated_at %></h6>
    </td>
  </tr>
</table>

<%= simple_form_for @bag do |f| %>
  <%= f.input :adv %>
  <%= f.input :description %>
  <%= f.input :link %>
  <%= f.button :submit %>
<% end %>

<table>
  <tr>
    <th>adv</th>
    <th>desc</th>
    <th>link</th>  
  </tr>
  <tr>
    <td><%= @bag.adv %></td>>
    <td><%= @bag.description %></td>>
    <td><%= @bag.link %></td>>
  </tr>
</table>
<p><i> <%= link_to 'mykit', welcome_index_path %> </i></p>

kit/app/views/bags/index.html.erb
<!-- kit index -->
<h2>my<strong><i>kit</i></strong></h2>
<p>pick your next adventure!<p>
<table>
  <tr>
    <th>adventure</th>
    <th>description</th>
    <th>link</th>
  </tr>
  <% @bags.each do |bag| %>
    <tr>
      <td><%= bag.adv %></td>
      <td><%= bag.description %></td>
      <td><%= bag.link %></td>
    </tr>
  <% end %>
</table>
<p><i> <%= link_to 'mykit', welcome_index_path %> </i></p>

kit/app/views/bags/new.html.erb
<!-- kit new -->
<h2>create <strong><i>kit</i></strong></h2>
<div class="kit-new-form">
  <%= simple_form_for @bag do |f| %>
    <%= f.label :adv, 'purpose of this kit?' %>
    <!-- maybe use amazon search of top self help topics for hint? -->
    <%= f.input :adv, required: true, label: false, placeholder: 'better travel, simpler love, less money, better exercise...' %>
    <%= f.label :adv, 'short description?' %>
    <%= f.input :description, label: false, placeholder: 'discoverying my third eye through fly fishing :P' %>
    <%= f.label :link, 'link?' %>
    <%= f.input :link, label: false, placeholder: 'reddit.com/r/sailing'%>
    <%= f.button :submit, 'save kit' %>
  <% end %>  
</div>

<div class="nav-btm">
  <ul>
    <li><%= link_to 'kit exchange', bags_path %></li>
    <li><%= link_to 'mykit', welcome_index_path %></li>
  </ul>
</div>

kit/app/views/bags/show.html.erb
<!-- kit show -->
<h2><a href="<%= @bag.link %>"><%= @bag.link %></a><strong> <i>kit</i></strong></h2><p><%= @bag.description %></p>
<%= link_to 'edit', edit_bag_path %>
<table>
  <tr>
    <th>created</th>
    <th>updated</th>
  </tr> 
  <td><%= @bag.created_at %></td> 
  <td><%= @bag.updated_at %></td> 
</table>
<p></p>
<p> <%= link_to 'kit exchange', bags_path %> </p>

kit/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <title>kit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= yield %>  
</body>
<!-- <i> <%= link_to 'mykit', welcome_index_path %> </i> -->
</html>

kit/app/views/welcome/index.html.erb
<h2>my<strong><i>kit</i></strong></h2>
<p>welcome back</p>
<p><i><%= link_to 'make a kit', new_bag_path %></i></p>
<p><i><%= link_to 'kit exchange', bags_path %></i></p>